language: python
python: 3.8
before_install:
- sudo apt-get install -y binutils libproj-dev gdal-bin
install: python -m pip install -r requirements.txt
script: python manage.py test --keepdb
deploy:
  skip_cleanup: true
  provider: heroku
  app: jedprojects
  run:
  - python manage.py makemigrations
  - python manage.py migrate
  - heroku ps:scale web=1
  on: master
  api_key: $HEROKU_AUTH_TOKEN
