language: python
python: 3.8
before_install:
- sudo apt-get install -y binutils libproj-dev gdal-bin
install: pip install -r requirements.txt
script: python manage.py test --keepdb
deploy:
  provider: heroku
  app: projects
  run:
  - python manage.py makemigrations
  - python manage.py migrate
  - heroku ps:scale web=1
  on: master
  api_key: f88ed770-70ed-47fc-b40c-e0ce2977651c
 
